### ISSUE TITLE
Add function to get all SFP information.

### ISSUE THREAD

**Issue by thomasbridge-gnetwork** [davama/napalm-nokia_olt#7]
I would like to extend the driver to include the parsing/returning of the output of the command:

show equipment transceiver-inventory detail

This is because that is the command that returns the serial numbers of the SFPs installed on the OLT.

**Comment by thomasbridge-gnetwork** [comment]
Just to clarify I'm happy to work on this - just wanted to check you were open to the idea!

**Comment by davama** [comment]
Hello @thomasbridge-gnetwork,

First off, thank you very much for your interest!
We would be happy to receive your contribution. Please submit a PR and reference this ticket at your earliest convenience and add me as a reviewer.

Best,
Dave
